import React from 'react';
import { BookOpen } from 'lucide-react';
import { UserProfile } from './types';
import { MathRenderer } from './MathRenderer';
import './PrintStyles.css';

interface AnswerPreviewProps {
  user: UserProfile;
  subject: string;
  classLevel: string;
  question: string;
  answer: string;
  id?: string;
}

export const AnswerPreview: React.FC<AnswerPreviewProps> = ({
  user,
  subject,
  classLevel,
  question,
  answer,
  id = 'print-content'
}) => {
  const date = new Date().toLocaleDateString('en-US', {
    weekday: 'long', year: 'numeric', month: 'long', day: 'numeric'
  });

  return (
    <div id={id} className="print-container">
      {/* Watermark */}
      <div className="print-watermark">BK ACADEMY AI</div>

      {/* Header */}
      <header className="print-header">
        <div className="print-logo">
          <div className="print-logo-icon">
            <BookOpen size={24} color="white" />
          </div>
          <div className="print-title">BK Academy</div>
        </div>
        <div className="print-meta">
          <p><strong>Student:</strong> {user.displayName}</p>
          <p><strong>Subject:</strong> {subject}</p>
          <p><strong>Class:</strong> {classLevel}</p>
          <p><strong>Date:</strong> {date}</p>
        </div>
      </header>

      {/* Body */}
      <main>
        <section className="print-question-box">
          <span className="print-label">Question</span>
          <div className="print-question-text">
            {question}
          </div>
        </section>

        <section className="print-answer-body">
          <span className="print-label" style={{ color: '#4f46e5', marginBottom: '10px' }}>Solution</span>
          <MathRenderer content={answer} className="text-justify" />
        </section>
      </main>

      {/* Footer */}
      <footer className="print-footer">
        <div>Generated by BK Academy AI System</div>
        <div>Page 1</div>
      </footer>
    </div>
  );
};