import React, { useState, useRef, useEffect } from 'react';
import { Camera, Send, X, Loader2, BrainCircuit, Download, FileText, Eye } from 'lucide-react';
import { SUBJECTS_NCTB, CLASSES, Question } from './types';
import { generateHomeworkSolution } from './GeminiService';
import { saveQuestion, checkDailyLimit } from './FirestoreService';
import { uploadImage } from './StorageService';
import { useAuth } from './AuthContext';
import { MathRenderer } from './MathRenderer';
import { AnswerPreview } from './AnswerPreview';
import { generatePdf } from './PdfGenerator';
import { getFounderSettings } from './AdminService';

export const Solver: React.FC = () => {
  const { user, refreshUserProfile } = useAuth();
  const [question, setQuestion] = useState('');
  const [subject, setSubject] = useState(SUBJECTS_NCTB[2]); // Math default
  const [classLevel, setClassLevel] = useState(user?.classLevel || CLASSES[9]);
  const [image, setImage] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [downloading, setDownloading] = useState(false);
  const [canDownload, setCanDownload] = useState(true);
  const [showPreview, setShowPreview] = useState(false);
  
  const fileInputRef = useRef<HTMLInputElement>(null);
  const bottomRef = useRef<HTMLDivElement>(null);

  // Check if admin enabled PDF downloads
  useEffect(() => {
    const checkSettings = async () => {
        const settings = await getFounderSettings();
        setCanDownload(settings.enablePdfDownload !== false);
    };
    checkSettings();
  }, []);

  const handleImageUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onloadend = () => {
        setImage(reader.result as string);
      };
      reader.readAsDataURL(file);
    }
  };

  const handleSolve = async () => {
    if ((!question.trim() && !image) || !user) return;

    setError(null);
    const canSolve = await checkDailyLimit(user);
    if (!canSolve) {
      setError("Daily limit reached! Upgrade to Premium for unlimited questions.");
      return;
    }

    setLoading(true);
    setResult(null);

    try {
      // 1. Solve with AI
      const answer = await generateHomeworkSolution(question, image || undefined, subject, classLevel);
      setResult(answer);

      // 2. Upload Image if exists (Async)
      let imageUrl: string | undefined = undefined;
      if (image) {
        try {
          imageUrl = await uploadImage(user.uid, image);
        } catch (e) { console.warn("Image upload failed", e); }
      }

      // 3. Save to Firestore
      const newQ: Question = {
        id: '', // Generated by Firestore (placeholder)
        userId: user.uid,
        subject,
        classLevel,
        questionText: question,
        answer,
        timestamp: Date.now(),
        ...(imageUrl ? { questionImage: imageUrl } : {})
      };
      await saveQuestion(user, newQ);
      
      // 4. Update UI
      await refreshUserProfile();
      setTimeout(() => bottomRef.current?.scrollIntoView({ behavior: 'smooth' }), 100);

    } catch (err) {
      console.error("Solver Error:", err);
      setError("Something went wrong. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  const handleDownloadPdf = async () => {
    if (!result || !user) return;
    setDownloading(true);
    try {
        const filename = `${subject}_${classLevel}_${new Date().toISOString().split('T')[0]}.pdf`;
        // Generate PDF from the visible modal element
        await generatePdf('pdf-export-container', filename);
    } catch (e) {
        console.error(e);
        alert("Failed to generate PDF. Please try again.");
    } finally {
        setDownloading(false);
    }
  };

  return (
    <div className="flex flex-col min-h-full bg-slate-50">
      {/* Header */}
      <header className="bg-white border-b border-slate-200 p-4 sticky top-0 z-10 shadow-sm">
        <div className="flex justify-between items-center">
          <h2 className="text-lg font-bold text-slate-800 font-bangla">AI Tutor</h2>
          <select 
            value={classLevel} 
            onChange={(e) => setClassLevel(e.target.value)}
            className="text-xs bg-slate-100 border-none rounded-lg py-1 px-2 text-slate-600 outline-none"
          >
            {CLASSES.map(c => <option key={c} value={c}>{c}</option>)}
          </select>
        </div>
      </header>

      <div className="p-4 space-y-4">
        {/* Subject Selector */}
        <div className="space-y-2">
          <label className="text-xs font-semibold text-slate-500 uppercase tracking-wider">Subject</label>
          <div className="flex overflow-x-auto no-scrollbar gap-2 pb-1">
            {SUBJECTS_NCTB.map((sub) => (
              <button
                key={sub}
                onClick={() => setSubject(sub)}
                className={`px-3 py-1.5 rounded-full text-xs font-medium whitespace-nowrap transition-all ${
                  subject === sub
                    ? 'bg-indigo-600 text-white shadow-md shadow-indigo-200'
                    : 'bg-white border border-slate-200 text-slate-600 hover:bg-slate-100'
                }`}
              >
                {sub}
              </button>
            ))}
          </div>
        </div>

        {/* Input Area */}
        <div className="bg-white rounded-2xl shadow-sm border border-slate-200 p-3 space-y-3 focus-within:ring-2 focus-within:ring-indigo-100 transition-all">
          <textarea
            className="w-full resize-none outline-none text-slate-700 placeholder-slate-400 min-h-[100px] bg-transparent text-sm leading-relaxed"
            placeholder={`Ask a question about ${subject}...`}
            value={question}
            onChange={(e) => setQuestion(e.target.value)}
          />

          {image && (
            <div className="relative inline-block group">
              <img src={image} alt="Upload" className="h-24 w-auto rounded-lg border border-slate-200 shadow-sm" />
              <button
                onClick={() => setImage(null)}
                className="absolute -top-2 -right-2 bg-red-500 text-white rounded-full p-1 shadow-sm hover:bg-red-600 transition-colors"
              >
                <X className="w-3 h-3" />
              </button>
            </div>
          )}

          <div className="flex justify-between items-center pt-2 border-t border-slate-100">
            <input
              type="file"
              ref={fileInputRef}
              accept="image/*"
              className="hidden"
              onChange={handleImageUpload}
            />
            <button
              onClick={() => fileInputRef.current?.click()}
              className="flex items-center space-x-2 text-slate-500 hover:text-indigo-600 transition p-2 rounded-lg hover:bg-slate-50"
            >
              <Camera className="w-5 h-5" />
              <span className="text-xs font-medium">Add Photo</span>
            </button>
            
            <button
              onClick={handleSolve}
              disabled={loading || (!question && !image)}
              className={`flex items-center space-x-2 px-5 py-2.5 rounded-xl text-white font-medium transition-all shadow-md ${
                loading || (!question && !image)
                  ? 'bg-slate-300 cursor-not-allowed shadow-none'
                  : 'bg-indigo-600 hover:bg-indigo-700 hover:shadow-lg shadow-indigo-200'
              }`}
            >
              {loading ? (
                <Loader2 className="w-4 h-4 animate-spin" />
              ) : (
                <>
                  <span className="text-sm">Solve</span>
                  <Send className="w-4 h-4" />
                </>
              )}
            </button>
          </div>
        </div>

        {/* Error Message */}
        {error && (
          <div className="bg-red-50 text-red-600 text-sm p-3 rounded-xl border border-red-100 animate-fade-in text-center">
            {error}
          </div>
        )}

        {/* Result Area */}
        {result && (
          <div className="bg-white rounded-2xl shadow-xl shadow-slate-200/50 border border-slate-100 overflow-hidden animate-fade-in mb-8">
            <div className="bg-gradient-to-r from-indigo-50 to-white px-5 py-4 border-b border-indigo-50 flex justify-between items-center">
              <div className="flex items-center gap-3">
                <div className="bg-indigo-100 p-1.5 rounded-lg">
                    <BrainCircuit className="w-5 h-5 text-indigo-600" />
                </div>
                <h3 className="font-bold text-slate-800 font-bangla">AI Explanation</h3>
              </div>
              
              {canDownload && (
                <button 
                  onClick={() => setShowPreview(true)}
                  className="flex items-center gap-2 text-xs font-bold text-indigo-600 bg-indigo-50 px-3 py-1.5 rounded-lg hover:bg-indigo-100 transition"
                >
                  <Eye className="w-3 h-3" />
                  Preview PDF
                </button>
              )}
            </div>
            
            <div className="p-6 text-slate-800">
              <MathRenderer content={result} />
            </div>
          </div>
        )}
        <div ref={bottomRef} />
      </div>

      {/* 📄 PDF Preview Modal */}
      {showPreview && result && user && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/80 backdrop-blur-sm p-4 animate-in fade-in">
          <div className="bg-slate-100 w-full h-full max-w-5xl rounded-2xl shadow-2xl overflow-hidden flex flex-col">
            
            {/* Modal Header */}
            <div className="bg-white p-4 border-b border-slate-200 flex justify-between items-center shadow-sm z-10">
              <h3 className="font-bold text-slate-700 flex items-center gap-2">
                  <FileText className="w-5 h-5 text-indigo-600"/> PDF Preview
              </h3>
              <div className="flex gap-2">
                  <button 
                    onClick={() => setShowPreview(false)} 
                    className="px-4 py-2 text-slate-600 hover:bg-slate-100 rounded-lg text-sm font-medium transition"
                  >
                    Close
                  </button>
                  <button 
                    onClick={handleDownloadPdf}
                    disabled={downloading}
                    className="px-4 py-2 bg-indigo-600 text-white rounded-lg text-sm font-bold hover:bg-indigo-700 transition shadow-lg shadow-indigo-200 flex items-center gap-2"
                  >
                    {downloading ? <Loader2 className="w-4 h-4 animate-spin"/> : <Download className="w-4 h-4"/>}
                    Download
                  </button>
              </div>
            </div>
            
            {/* Modal Body (Scrollable A4 Preview) */}
            <div className="flex-1 overflow-auto p-4 md:p-8 flex justify-center bg-slate-500/10">
               {/* 
                  Wrapper for centering. 
                  We do NOT scale here to ensure html2pdf captures full resolution text.
                  User scrolls horizontally on mobile if needed.
               */}
               <div className="bg-white shadow-2xl shrink-0">
                  <AnswerPreview 
                    id="pdf-export-container"
                    user={user} 
                    subject={subject} 
                    classLevel={classLevel} 
                    question={question || (image ? "Image Question" : "")} 
                    answer={result} 
                  />
               </div>
            </div>

          </div>
        </div>
      )}
    </div>
  );
};